# Generated by Django 5.2.6 on 2025-09-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_contact', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('industry', models.CharField(blank=True, choices=[('Tech', 'Technology'), ('Finance', 'Finance'), ('Health', 'Healthcare'), ('Edu', 'Education'), ('Retail', 'Retail'), ('Eng', 'Engineering'), ('Auto', 'Automotive'), ('Food', 'Food & Beverage'), ('Media', 'Media & Entertainment'), ('Con', 'Construction'), ('Other', 'Other')], max_length=100, null=True)),
                ('location', models.CharField(blank=True, choices=[('East of England', 'East of England'), ('East Midlands', 'East Midlands'), ('London', 'London'), ('North East', 'North East'), ('North West', 'North West'), ('South East', 'South East'), ('South West', 'South West'), ('West Midlands', 'West Midlands'), ('Yorkshire and the Humber', 'Yorkshire and the Humber'), ('Scotland', 'Scotland'), ('Wales', 'Wales'), ('Northern Ireland', 'Northern Ireland'), ('Other', 'Other')], max_length=100, null=True)),
                ('account_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending'), ('Archived', 'Archived'), ('Prospect', 'Prospect'), ('Other', 'Other')], max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
