# Generated by Django 5.2.6 on 2025-09-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuetrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending'), ('Archived', 'Archived'), ('Prospect', 'Prospect'), ('Other', 'Other')], default='Active', max_length=50, null=True),
        ),
    ]
