# Generated by Django 5.2.6 on 2025-09-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuetrack', '0005_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
