# Generated by Django 5.2.6 on 2025-09-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuetrack', '0006_provider_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='archived',
        ),
        migrations.AddField(
            model_name='provider',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
