# Generated by Django 5.2.6 on 2025-09-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuetrack', '0008_alter_provider_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External'), ('Partner', 'Partner')], default='External', max_length=20),
        ),
    ]
