# Generated by Django 5.2.6 on 2025-09-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuetrack', '0009_alter_provider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='industry',
            field=models.CharField(blank=True, choices=[('Tech', 'Technology'), ('Finance', 'Finance'), ('Health', 'Healthcare'), ('Edu', 'Education'), ('Retail', 'Retail'), ('Eng', 'Engineering'), ('Auto', 'Automotive'), ('Food', 'Food & Beverage'), ('Media', 'Media & Entertainment'), ('Con', 'Construction'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
