# Generated by Django 5.2.6 on 2025-09-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valuetrack', '0011_alter_provider_industry_service_serviceprovider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='service',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='provider',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
    ]
