# Generated by Django 5.2.6 on 2025-09-25 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuetrack', '0011_alter_provider_industry_service_serviceprovider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='valuetrack.provider'),
        ),
        migrations.AddConstraint(
            model_name='serviceprovider',
            constraint=models.UniqueConstraint(fields=('service', 'provider'), name='unique_service_provider'),
        ),
    ]
