# Generated by Django 5.2.6 on 2025-09-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuetrack', '0013_category_service_solution_problemsolutionlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, choices=[('Tech', 'Technology'), ('Finance', 'Finance'), ('Health', 'Healthcare'), ('Edu', 'Education'), ('Retail', 'Retail'), ('Eng', 'Engineering'), ('Auto', 'Automotive'), ('Food', 'Food & Beverage'), ('Media', 'Media & Entertainment'), ('Con', 'Construction'), ('Manu', 'Manufacturing'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='industry',
            field=models.CharField(blank=True, choices=[('Tech', 'Technology'), ('Finance', 'Finance'), ('Health', 'Healthcare'), ('Edu', 'Education'), ('Retail', 'Retail'), ('Eng', 'Engineering'), ('Auto', 'Automotive'), ('Food', 'Food & Beverage'), ('Media', 'Media & Entertainment'), ('Con', 'Construction'), ('Manu', 'Manufacturing'), ('Other', 'Other')], default='Other', max_length=100, null=True),
        ),
    ]
