# Generated by Django 5.2.6 on 2025-09-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuetrack', '0014_alter_customer_industry_alter_provider_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='root_cause',
            field=models.TextField(blank=True, null=True),
        ),
    ]
