# Generated by Django 5.2.6 on 2025-09-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuetrack', '0015_problemstatement_root_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsolutionlink',
            name='lessons_learned',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemsolutionlink',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemsolutionlink',
            name='strategy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
